security:
  oauth2:
    client:
      client: sql_trainer
      client_version: 0.0.0
      clientId: a1fd93b05eaa82f429d1396d0097b2bf5e479683c79693b53f0b054279778c24
      clientSecret: b7887531bc47d4aed8f81899a7378670898e8e7f435c489b323c3d4c5d99c538
      accessTokenUri: https://tmc.mooc.fi/oauth/token
      userAuthorizationUri: https://tmc.mooc.fi/oauth/authorize
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://tmc.mooc.fi/api/beta/participant/